from setuptools import setup
import os
 
setup(
    name='runclim',
    version='0.1.0',
    packages=['runclim',],
    zip_safe=False,
    install_requires=["numpy>=1.16","matplotlib","scipy","meson","ninja","Pillow"],
    extras_require = {"netCDF4": ["netCDF4"],
                      "HDF5": ["h5py"],
                      "petitRADTRANS": ["petitRADTRANS>=2.4"]},
    include_package_data=True,
    exclude_package_data={'': ['runclim/cat*',
                               'runclim/Cat_UG_00',
                               'runclim/glacier',
                               'runclim/images',
                               'runclim/octave',
                               'runclim/Plasim_Report',
                               'runclim/Plasim_RM_16', 
                               'runclim/Plasim_UG_16',
                               'runclim/puma',
                               'runclim/Puma_UG_17',
                               'runclim/ug_cat_00',
                               'runclim/sam',
                               'runclim/lsg',
                               'runclim/tools',
                               'runclim/plasim/run/*.sra']},
    author='ArvAcl',
    author_email='arvillacl16@gmail.com',
    license='GNU General Public License',
    license_files=["LICENSE.TXT",],
    url='https://github.com/arvillacl16-bit/runclim',
    description='Exoplanet GCM',
    )
